"""add hash_algorithm column

Revision ID: 8ae6011e3efa
Revises: a8f50ea9e8f1
Create Date: 2025-12-06 16:22:06.979499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae6011e3efa'
down_revision = 'a8f50ea9e8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_algorithm', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hash_algorithm')

    # ### end Alembic commands ###
